server:
  port: 8010
spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/ROAOR1/config-server.git
          username:
          password:
          search-paths: config #要搜索的路径，填我们刚刚创建的文件夹
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8001/eureka/,http://localhost:8002/eureka/