server:
  port: 8003
spring:
  application:
    name: eureka-client
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8001/eureka/,http://localhost:8002/eureka/
management:
  endpoints:
    web:
      exposure:
        include: hystrix.stream