server:
  port: 8002
spring:
  application:
    name: eureka-server
eureka:
  instance:
    hostname: eureka-server-8002
  client:
    service-url:
      defaultZone: http://localhost:8001/eureka/
    register-with-eureka: true
    fetch-registry: true
