server:
  port: 8011
spring:
  application:
    name: config-client
  cloud:
    bus:
      enabled: true
      trace:
        enabled: true
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
data: ${spring.profiles.active} #用这个来加载配置中心中的数据