server:
  port: 8008
spring:
  application:
    name: zuul-client
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8001/eureka/,http://localhost:8002/eureka/
zuul:
  routes:
    eureka-client: #可以任意，一般都会和服务名相同
      path: /eureka-client/** #访问路径
      serviceId: eureka-client  #会映射到这个服务上
      #url: http://localhost:8003 #也可以直接映射到某个地址，一般不会这么做
