server:
  port: 8013
spring:
  application:
    name: stream-producer
  cloud:
    stream:
      binders: #在此处配置要绑定的rabbitmq的服务信息
        myrabbit: #自定义的名称
          type: rabbit #消息组件类型
          environment: #设置rabbitmq的相关的环境配置
            spring:
              rabbitmq:
                host: 127.0.0.1
                port: 5672
                username: guest
                password: guest
      bindings:
        myOutput: #绑定的通道，这里使用的是stream提供的输出通道
          destination: msg #发送的目的地
          content-type: application/json #消息类型