server:
  port: 8001
spring:
  application:
    name: eureka-server
eureka:
  instance:
    hostname: eureka-server-8001
  client:
    service-url:
      defaultZone: http://localhost:8002/eureka/
    register-with-eureka: true
    fetch-registry: true
