server:
  port: 8009
spring:
  application:
    name: config-server
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
  cloud:
    config:
      server:
        git:
          uri: https://github.com/ROAOR1/config-server.git
          username:
          password:
          search-paths: config #要搜索的路径，填我们刚刚创建的文件夹
    bus:
      enabled: true
      trace:
        enabled: true
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8001/eureka/,http://localhost:8002/eureka/
management:
  endpoints:
    web:
      exposure:
        include: bus-refresh